use std::{collections::HashSet, sync::OnceLock};

use crate::model::{ItemKind, PickerItem};

static CATALOG: OnceLock<Vec<PickerItem>> = OnceLock::new();

/// Returns the complete in-memory picker catalog.
///
/// Emoji data is generated by the `emojis` crate from Unicode Emoji 17.0 data.
/// We include the base RGI set plus every skin-tone sequence exposed by the
/// Unicode dataset, while preserving the crate's CLDR/Unicode ordering.
pub fn items() -> &'static [PickerItem] {
    CATALOG.get_or_init(build_catalog).as_slice()
}

fn build_catalog() -> Vec<PickerItem> {
    let mut out = Vec::with_capacity(4500 + OTHER_ITEMS.len());
    let mut seen = HashSet::<&'static str>::with_capacity(4500);

    for emoji in emojis::iter() {
        push_emoji(&mut out, &mut seen, emoji);
        if let Some(tones) = emoji.skin_tones() {
            for toned in tones {
                push_emoji(&mut out, &mut seen, toned);
            }
        }
    }

    out.extend_from_slice(OTHER_ITEMS);
    out
}

fn push_emoji(
    out: &mut Vec<PickerItem>,
    seen: &mut HashSet<&'static str>,
    emoji: &'static emojis::Emoji,
) {
    let content = emoji.as_str();
    if !seen.insert(content) {
        return;
    }

    out.push(PickerItem {
        kind: ItemKind::Emoji,
        title: emoji.name(),
        content,
        keywords: emoji_aliases(content),
    });
}

fn emoji_aliases(content: &str) -> &'static str {
    match content {
        "😀" | "😃" | "😄" | "😁" | "😆" | "😂" | "🤣" => "خنده لبخند خوشحال",
        "😊" | "🙂" => "لبخند خوشحال",
        "😍" | "🥰" | "❤️" | "❤" => "عشق قلب دوست داشتن",
        "😘" => "بوس عشق",
        "😢" | "😭" => "گریه غم ناراحت",
        "😠" | "😡" | "🤬" => "عصبانی خشم",
        "🤔" => "فکر تفکر",
        "👋" => "سلام خداحافظ دست",
        "👍" => "لایک تایید بله",
        "👎" => "دیسلایک رد نه",
        "🙏" => "تشکر ممنون دعا لطفا",
        "🔥" => "آتش داغ",
        "✅" => "تایید انجام درست",
        "❌" => "خطا رد اشتباه",
        "⚠️" => "هشدار اخطار",
        "🇮🇷" => "ایران پرچم",
        _ => "",
    }
}

pub static OTHER_ITEMS: &[PickerItem] = &[
    // Kaomoji
    PickerItem { kind: ItemKind::Kaomoji, title: "Shrug", content: r#"¯\_(ツ)_/¯"#, keywords: "shrug whatever شانه" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Table flip", content: "(╯°□°)╯︵ ┻━┻", keywords: "table flip angry میز خشم" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Table restore", content: "┬─┬ ノ( ゜-゜ノ)", keywords: "table restore calm میز" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Hug", content: "(づ｡◕‿‿◕｡)づ", keywords: "hug love بغل" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Disapproval", content: "ಠ_ಠ", keywords: "disapproval stare نگاه" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Bear", content: "ʕ•ᴥ•ʔ", keywords: "bear animal خرس" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Fight", content: "(ง'̀-'́)ง", keywords: "fight angry مشت" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Happy", content: "(＾▽＾)", keywords: "happy smile خوشحال" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Cute", content: "(◕‿◕)", keywords: "cute happy بامزه" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Sad", content: "(╥﹏╥)", keywords: "sad cry غم گریه" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Love", content: "(♥‿♥)", keywords: "love heart عشق" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Confused", content: "(・_・ヾ", keywords: "confused hmm گیج" },

    // ASCII art
    PickerItem { kind: ItemKind::Ascii, title: "Cat", content: " /\\_/\\\n( o.o )\n > ^ <", keywords: "cat animal گربه" },
    PickerItem { kind: ItemKind::Ascii, title: "Box", content: "+-------------+\n| HELLO WORLD |\n+-------------+", keywords: "box hello banner کادر" },
    PickerItem { kind: ItemKind::Ascii, title: "Arrow", content: "----->", keywords: "arrow right فلش" },
    PickerItem { kind: ItemKind::Ascii, title: "Divider", content: "------------------------------", keywords: "divider line separator جداکننده خط" },
    PickerItem { kind: ItemKind::Ascii, title: "Small heart", content: "<3", keywords: "heart love قلب" },
    PickerItem { kind: ItemKind::Ascii, title: "Success box", content: "[ OK ]", keywords: "ok success تایید" },

    // Ready text snippets
    PickerItem { kind: ItemKind::Snippet, title: "Persian greeting", content: "سلام، وقت بخیر", keywords: "hello greeting سلام وقت بخیر" },
    PickerItem { kind: ItemKind::Snippet, title: "Persian thanks", content: "با تشکر از شما", keywords: "thanks thank you تشکر ممنون" },
    PickerItem { kind: ItemKind::Snippet, title: "Persian follow-up", content: "لطفاً نتیجه را اطلاع دهید.", keywords: "follow up result پیگیری نتیجه" },
    PickerItem { kind: ItemKind::Snippet, title: "Persian review", content: "در اسرع وقت بررسی خواهد شد.", keywords: "review soon بررسی" },
    PickerItem { kind: ItemKind::Snippet, title: "English greeting", content: "Hello, hope you're doing well.", keywords: "hello greeting email" },
    PickerItem { kind: ItemKind::Snippet, title: "English thanks", content: "Thank you for your response.", keywords: "thanks response email" },
    PickerItem { kind: ItemKind::Snippet, title: "Best regards", content: "Best regards,", keywords: "email closing regards" },
    PickerItem { kind: ItemKind::Snippet, title: "Code TODO", content: "TODO: ", keywords: "code todo developer" },

    // Symbols
    PickerItem { kind: ItemKind::Symbol, title: "Copyright", content: "©", keywords: "copyright کپی رایت" },
    PickerItem { kind: ItemKind::Symbol, title: "Registered", content: "®", keywords: "registered trademark" },
    PickerItem { kind: ItemKind::Symbol, title: "Trademark", content: "™", keywords: "trademark" },
    PickerItem { kind: ItemKind::Symbol, title: "Degree", content: "°", keywords: "degree temperature درجه" },
    PickerItem { kind: ItemKind::Symbol, title: "Plus minus", content: "±", keywords: "plus minus math مثبت منفی" },
    PickerItem { kind: ItemKind::Symbol, title: "Multiply", content: "×", keywords: "multiply times math ضرب" },
    PickerItem { kind: ItemKind::Symbol, title: "Divide", content: "÷", keywords: "divide math تقسیم" },
    PickerItem { kind: ItemKind::Symbol, title: "Approximately", content: "≈", keywords: "approximately math تقریبا" },
    PickerItem { kind: ItemKind::Symbol, title: "Not equal", content: "≠", keywords: "not equal math نامساوی" },
    PickerItem { kind: ItemKind::Symbol, title: "Less equal", content: "≤", keywords: "less equal math کوچکتر" },
    PickerItem { kind: ItemKind::Symbol, title: "Greater equal", content: "≥", keywords: "greater equal math بزرگتر" },
    PickerItem { kind: ItemKind::Symbol, title: "Infinity", content: "∞", keywords: "infinity math بی نهایت" },
    PickerItem { kind: ItemKind::Symbol, title: "Right arrow", content: "→", keywords: "right arrow فلش راست" },
    PickerItem { kind: ItemKind::Symbol, title: "Left arrow", content: "←", keywords: "left arrow فلش چپ" },
    PickerItem { kind: ItemKind::Symbol, title: "Up arrow", content: "↑", keywords: "up arrow فلش بالا" },
    PickerItem { kind: ItemKind::Symbol, title: "Down arrow", content: "↓", keywords: "down arrow فلش پایین" },
    PickerItem { kind: ItemKind::Symbol, title: "Bullet", content: "•", keywords: "bullet dot نقطه" },
    PickerItem { kind: ItemKind::Symbol, title: "Middle dot", content: "·", keywords: "middle dot نقطه" },
    PickerItem { kind: ItemKind::Symbol, title: "Section", content: "§", keywords: "section paragraph بخش" },
    PickerItem { kind: ItemKind::Symbol, title: "Paragraph", content: "¶", keywords: "paragraph pilcrow پاراگراف" },
];
