use std::{collections::HashSet, sync::OnceLock};

use crate::model::{ItemKind, PickerItem};

static CATALOG: OnceLock<Vec<PickerItem>> = OnceLock::new();

/// Returns the complete in-memory picker catalog.
///
/// Emoji data is generated by the `emojis` crate from Unicode Emoji 17.0 data.
/// We include the base RGI set plus every skin-tone sequence exposed by the
/// Unicode dataset, while preserving the crate's CLDR/Unicode ordering.
pub fn items() -> &'static [PickerItem] {
    CATALOG.get_or_init(build_catalog).as_slice()
}

fn build_catalog() -> Vec<PickerItem> {
    let mut out = Vec::with_capacity(4500 + OTHER_ITEMS.len());
    let mut seen = HashSet::<&'static str>::with_capacity(4500);

    for emoji in emojis::iter() {
        push_emoji(&mut out, &mut seen, emoji);
        if let Some(tones) = emoji.skin_tones() {
            for toned in tones {
                push_emoji(&mut out, &mut seen, toned);
            }
        }
    }

    out.extend_from_slice(OTHER_ITEMS);
    out
}

fn push_emoji(
    out: &mut Vec<PickerItem>,
    seen: &mut HashSet<&'static str>,
    emoji: &'static emojis::Emoji,
) {
    let content = emoji.as_str();
    if !seen.insert(content) {
        return;
    }

    out.push(PickerItem {
        kind: ItemKind::Emoji,
        title: emoji.name(),
        content,
        keywords: emoji_aliases(content),
    });
}

fn emoji_aliases(content: &str) -> &'static str {
    match content {
        "😀" | "😃" | "😄" | "😁" | "😆" | "😂" | "🤣" => "laugh smile happy grin",
        "😊" | "🙂" => "smile happy friendly",
        "😍" | "🥰" | "❤️" | "❤" => "love heart affection",
        "😘" => "kiss love",
        "😢" | "😭" => "cry sad tears",
        "😠" | "😡" | "🤬" => "angry rage mad",
        "🤔" => "think thinking hmm",
        "👋" => "hello goodbye wave hand",
        "👍" => "like approve yes good",
        "👎" => "dislike reject no bad",
        "🙏" => "thanks please prayer gratitude",
        "🔥" => "fire hot flame",
        "✅" => "check confirm done correct",
        "❌" => "error reject wrong cross",
        "⚠️" => "warning alert caution",
        "🇮🇷" => "iran flag",
        _ => "",
    }
}

pub static OTHER_ITEMS: &[PickerItem] = &[
    // Kaomoji
    PickerItem { kind: ItemKind::Kaomoji, title: "Shrug", content: r#"¯\_(ツ)_/¯"#, keywords: "shrug whatever" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Table flip", content: "(╯°□°)╯︵ ┻━┻", keywords: "table flip angry" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Table restore", content: "┬─┬ ノ( ゜-゜ノ)", keywords: "table restore calm" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Hug", content: "(づ｡◕‿‿◕｡)づ", keywords: "hug love" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Disapproval", content: "ಠ_ಠ", keywords: "disapproval stare" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Bear", content: "ʕ•ᴥ•ʔ", keywords: "bear animal" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Fight", content: "(ง'̀-'́)ง", keywords: "fight angry" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Happy", content: "(＾▽＾)", keywords: "happy smile" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Cute", content: "(◕‿◕)", keywords: "cute happy" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Sad", content: "(╥﹏╥)", keywords: "sad cry" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Love", content: "(♥‿♥)", keywords: "love heart" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Confused", content: "(・_・ヾ", keywords: "confused hmm" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Multiline hello", content: "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧\nHello!", keywords: "hello multiline sparkle" },

    // ASCII art
    PickerItem { kind: ItemKind::Ascii, title: "Cat", content: " /\\_/\\\n( o.o )\n > ^ <", keywords: "cat animal" },
    PickerItem { kind: ItemKind::Ascii, title: "Box", content: "+-------------+\n| HELLO WORLD |\n+-------------+", keywords: "box hello banner" },
    PickerItem { kind: ItemKind::Ascii, title: "Arrow", content: "----->", keywords: "arrow right" },
    PickerItem { kind: ItemKind::Ascii, title: "Divider", content: "------------------------------", keywords: "divider line separator" },
    PickerItem { kind: ItemKind::Ascii, title: "Small heart", content: "<3", keywords: "heart love" },
    PickerItem { kind: ItemKind::Ascii, title: "Success box", content: "[ OK ]", keywords: "ok success" },
    PickerItem { kind: ItemKind::Ascii, title: "Robot", content: "  [::]\n /|__|\\\n  /  \\", keywords: "robot multiline art" },

    // Ready text snippets
    PickerItem { kind: ItemKind::Snippet, title: "Greeting", content: "Hello, hope you're doing well.", keywords: "hello greeting email" },
    PickerItem { kind: ItemKind::Snippet, title: "Thanks", content: "Thank you for your response.", keywords: "thanks response email" },
    PickerItem { kind: ItemKind::Snippet, title: "Follow up", content: "Please let me know if you have any questions.", keywords: "follow up questions email" },
    PickerItem { kind: ItemKind::Snippet, title: "Review soon", content: "I'll review this and get back to you shortly.", keywords: "review soon reply" },
    PickerItem { kind: ItemKind::Snippet, title: "Take a look", content: "Could you please take a look when you have a moment?", keywords: "request review look" },
    PickerItem { kind: ItemKind::Snippet, title: "Sounds good", content: "Sounds good, thank you!", keywords: "agree thanks" },
    PickerItem { kind: ItemKind::Snippet, title: "Best regards", content: "Best regards,", keywords: "email closing regards" },
    PickerItem { kind: ItemKind::Snippet, title: "Code TODO", content: "TODO: ", keywords: "code todo developer" },
    PickerItem { kind: ItemKind::Snippet, title: "Multiline reply", content: "Hello,\n\nThanks for the update. I'll review it and get back to you soon.\n\nBest regards,", keywords: "multiline email reply template" },

    // Symbols
    PickerItem { kind: ItemKind::Symbol, title: "Copyright", content: "©", keywords: "copyright" },
    PickerItem { kind: ItemKind::Symbol, title: "Registered", content: "®", keywords: "registered trademark" },
    PickerItem { kind: ItemKind::Symbol, title: "Trademark", content: "™", keywords: "trademark" },
    PickerItem { kind: ItemKind::Symbol, title: "Degree", content: "°", keywords: "degree temperature" },
    PickerItem { kind: ItemKind::Symbol, title: "Plus minus", content: "±", keywords: "plus minus math" },
    PickerItem { kind: ItemKind::Symbol, title: "Multiply", content: "×", keywords: "multiply times math" },
    PickerItem { kind: ItemKind::Symbol, title: "Divide", content: "÷", keywords: "divide math" },
    PickerItem { kind: ItemKind::Symbol, title: "Approximately", content: "≈", keywords: "approximately math" },
    PickerItem { kind: ItemKind::Symbol, title: "Not equal", content: "≠", keywords: "not equal math" },
    PickerItem { kind: ItemKind::Symbol, title: "Less equal", content: "≤", keywords: "less equal math" },
    PickerItem { kind: ItemKind::Symbol, title: "Greater equal", content: "≥", keywords: "greater equal math" },
    PickerItem { kind: ItemKind::Symbol, title: "Infinity", content: "∞", keywords: "infinity math" },
    PickerItem { kind: ItemKind::Symbol, title: "Right arrow", content: "→", keywords: "right arrow" },
    PickerItem { kind: ItemKind::Symbol, title: "Left arrow", content: "←", keywords: "left arrow" },
    PickerItem { kind: ItemKind::Symbol, title: "Up arrow", content: "↑", keywords: "up arrow" },
    PickerItem { kind: ItemKind::Symbol, title: "Down arrow", content: "↓", keywords: "down arrow" },
    PickerItem { kind: ItemKind::Symbol, title: "Bullet", content: "•", keywords: "bullet dot" },
    PickerItem { kind: ItemKind::Symbol, title: "Middle dot", content: "·", keywords: "middle dot" },
    PickerItem { kind: ItemKind::Symbol, title: "Section", content: "§", keywords: "section paragraph" },
    PickerItem { kind: ItemKind::Symbol, title: "Paragraph", content: "¶", keywords: "paragraph pilcrow" },
];
