use crate::model::{ItemKind, PickerItem};

pub static ITEMS: &[PickerItem] = &[
    // Emoji
    PickerItem { kind: ItemKind::Emoji, title: "Grinning", content: "😀", keywords: "grin happy smile خنده لبخند" },
    PickerItem { kind: ItemKind::Emoji, title: "Smiley", content: "😃", keywords: "happy smile joy خوشحال لبخند" },
    PickerItem { kind: ItemKind::Emoji, title: "Smile", content: "😄", keywords: "happy smile joy خنده" },
    PickerItem { kind: ItemKind::Emoji, title: "Beaming", content: "😁", keywords: "teeth happy grin دندان خنده" },
    PickerItem { kind: ItemKind::Emoji, title: "Laughing", content: "😆", keywords: "laugh happy خنده" },
    PickerItem { kind: ItemKind::Emoji, title: "Sweat smile", content: "😅", keywords: "sweat smile nervous عرق لبخند" },
    PickerItem { kind: ItemKind::Emoji, title: "Tears of joy", content: "😂", keywords: "laugh cry joy tears خنده گریه" },
    PickerItem { kind: ItemKind::Emoji, title: "Rolling laugh", content: "🤣", keywords: "rofl laugh خنده" },
    PickerItem { kind: ItemKind::Emoji, title: "Warm smile", content: "😊", keywords: "smile blush happy لبخند" },
    PickerItem { kind: ItemKind::Emoji, title: "Halo", content: "😇", keywords: "angel innocent halo فرشته" },
    PickerItem { kind: ItemKind::Emoji, title: "Wink", content: "😉", keywords: "wink playful چشمک" },
    PickerItem { kind: ItemKind::Emoji, title: "Heart eyes", content: "😍", keywords: "love heart eyes عشق قلب" },
    PickerItem { kind: ItemKind::Emoji, title: "Hearts", content: "🥰", keywords: "love hearts affection عشق قلب" },
    PickerItem { kind: ItemKind::Emoji, title: "Kiss", content: "😘", keywords: "kiss love بوس عشق" },
    PickerItem { kind: ItemKind::Emoji, title: "Cool", content: "😎", keywords: "sunglasses cool عینک" },
    PickerItem { kind: ItemKind::Emoji, title: "Thinking", content: "🤔", keywords: "think hmm فکر" },
    PickerItem { kind: ItemKind::Emoji, title: "Neutral", content: "😐", keywords: "neutral blank بی تفاوت" },
    PickerItem { kind: ItemKind::Emoji, title: "Unamused", content: "😒", keywords: "unamused annoyed ناراحت" },
    PickerItem { kind: ItemKind::Emoji, title: "Sad", content: "😢", keywords: "sad cry tear غم گریه" },
    PickerItem { kind: ItemKind::Emoji, title: "Crying", content: "😭", keywords: "cry sob sad گریه غم" },
    PickerItem { kind: ItemKind::Emoji, title: "Angry", content: "😠", keywords: "angry mad عصبانی" },
    PickerItem { kind: ItemKind::Emoji, title: "Rage", content: "😡", keywords: "rage angry عصبانی خشم" },
    PickerItem { kind: ItemKind::Emoji, title: "Surprised", content: "😮", keywords: "surprise wow تعجب" },
    PickerItem { kind: ItemKind::Emoji, title: "Party", content: "🥳", keywords: "party birthday celebrate جشن تولد" },
    PickerItem { kind: ItemKind::Emoji, title: "Thumbs up", content: "👍", keywords: "thumb up yes like تایید لایک" },
    PickerItem { kind: ItemKind::Emoji, title: "Thumbs down", content: "👎", keywords: "thumb down no dislike رد" },
    PickerItem { kind: ItemKind::Emoji, title: "OK", content: "👌", keywords: "ok hand تایید" },
    PickerItem { kind: ItemKind::Emoji, title: "Clap", content: "👏", keywords: "clap applause تشویق" },
    PickerItem { kind: ItemKind::Emoji, title: "Hands", content: "🙏", keywords: "please pray thanks تشکر دعا" },
    PickerItem { kind: ItemKind::Emoji, title: "Wave", content: "👋", keywords: "wave hello bye سلام خداحافظ" },
    PickerItem { kind: ItemKind::Emoji, title: "Flex", content: "💪", keywords: "strong muscle قدرت" },
    PickerItem { kind: ItemKind::Emoji, title: "Eyes", content: "👀", keywords: "eyes look دیدن چشم" },
    PickerItem { kind: ItemKind::Emoji, title: "Red heart", content: "❤️", keywords: "heart love red قلب عشق" },
    PickerItem { kind: ItemKind::Emoji, title: "Broken heart", content: "💔", keywords: "heart broken sad قلب شکسته" },
    PickerItem { kind: ItemKind::Emoji, title: "Fire", content: "🔥", keywords: "fire hot lit آتش" },
    PickerItem { kind: ItemKind::Emoji, title: "Sparkles", content: "✨", keywords: "sparkle shine ستاره درخشش" },
    PickerItem { kind: ItemKind::Emoji, title: "Star", content: "⭐", keywords: "star favorite ستاره" },
    PickerItem { kind: ItemKind::Emoji, title: "Check", content: "✅", keywords: "check done yes تایید انجام" },
    PickerItem { kind: ItemKind::Emoji, title: "Cross", content: "❌", keywords: "cross no error خطا رد" },
    PickerItem { kind: ItemKind::Emoji, title: "Warning", content: "⚠️", keywords: "warning alert هشدار" },
    PickerItem { kind: ItemKind::Emoji, title: "Rocket", content: "🚀", keywords: "rocket launch fast موشک" },
    PickerItem { kind: ItemKind::Emoji, title: "Bulb", content: "💡", keywords: "idea bulb light ایده" },
    PickerItem { kind: ItemKind::Emoji, title: "Pin", content: "📌", keywords: "pin location note سنجاق" },
    PickerItem { kind: ItemKind::Emoji, title: "Calendar", content: "📅", keywords: "calendar date تقویم تاریخ" },
    PickerItem { kind: ItemKind::Emoji, title: "Phone", content: "📱", keywords: "phone mobile موبایل" },
    PickerItem { kind: ItemKind::Emoji, title: "Computer", content: "💻", keywords: "laptop computer code لپتاپ" },
    PickerItem { kind: ItemKind::Emoji, title: "Coffee", content: "☕", keywords: "coffee drink قهوه" },
    PickerItem { kind: ItemKind::Emoji, title: "Gift", content: "🎁", keywords: "gift present هدیه" },
    PickerItem { kind: ItemKind::Emoji, title: "Birthday", content: "🎂", keywords: "cake birthday تولد کیک" },
    PickerItem { kind: ItemKind::Emoji, title: "Iran", content: "🇮🇷", keywords: "iran flag ایران پرچم" },

    // Kaomoji
    PickerItem { kind: ItemKind::Kaomoji, title: "Shrug", content: r#"¯\_(ツ)_/¯"#, keywords: "shrug whatever شانه" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Table flip", content: "(╯°□°)╯︵ ┻━┻", keywords: "table flip angry میز خشم" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Table restore", content: "┬─┬ ノ( ゜-゜ノ)", keywords: "table restore calm میز" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Hug", content: "(づ｡◕‿‿◕｡)づ", keywords: "hug love بغل" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Disapproval", content: "ಠ_ಠ", keywords: "disapproval stare نگاه" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Bear", content: "ʕ•ᴥ•ʔ", keywords: "bear animal خرس" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Fight", content: "(ง'̀-'́)ง", keywords: "fight angry مشت" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Happy", content: "(＾▽＾)", keywords: "happy smile خوشحال" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Cute", content: "(◕‿◕)", keywords: "cute happy بامزه" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Sad", content: "(╥﹏╥)", keywords: "sad cry غم گریه" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Love", content: "(♥‿♥)", keywords: "love heart عشق" },
    PickerItem { kind: ItemKind::Kaomoji, title: "Confused", content: "(・_・ヾ", keywords: "confused hmm گیج" },

    // ASCII art
    PickerItem { kind: ItemKind::Ascii, title: "Cat", content: " /\\_/\\\n( o.o )\n > ^ <", keywords: "cat animal گربه" },
    PickerItem { kind: ItemKind::Ascii, title: "Box", content: "+-------------+\n| HELLO WORLD |\n+-------------+", keywords: "box hello banner کادر" },
    PickerItem { kind: ItemKind::Ascii, title: "Arrow", content: "----->", keywords: "arrow right فلش" },
    PickerItem { kind: ItemKind::Ascii, title: "Divider", content: "------------------------------", keywords: "divider line separator جداکننده خط" },
    PickerItem { kind: ItemKind::Ascii, title: "Small heart", content: "<3", keywords: "heart love قلب" },
    PickerItem { kind: ItemKind::Ascii, title: "Success box", content: "[ OK ]", keywords: "ok success تایید" },

    // Ready text snippets
    PickerItem { kind: ItemKind::Snippet, title: "Persian greeting", content: "سلام، وقت بخیر", keywords: "hello greeting سلام وقت بخیر" },
    PickerItem { kind: ItemKind::Snippet, title: "Persian thanks", content: "با تشکر از شما", keywords: "thanks thank you تشکر ممنون" },
    PickerItem { kind: ItemKind::Snippet, title: "Persian follow-up", content: "لطفاً نتیجه را اطلاع دهید.", keywords: "follow up result پیگیری نتیجه" },
    PickerItem { kind: ItemKind::Snippet, title: "Persian review", content: "در اسرع وقت بررسی خواهد شد.", keywords: "review soon بررسی" },
    PickerItem { kind: ItemKind::Snippet, title: "English greeting", content: "Hello, hope you're doing well.", keywords: "hello greeting email" },
    PickerItem { kind: ItemKind::Snippet, title: "English thanks", content: "Thank you for your response.", keywords: "thanks response email" },
    PickerItem { kind: ItemKind::Snippet, title: "Best regards", content: "Best regards,", keywords: "email closing regards" },
    PickerItem { kind: ItemKind::Snippet, title: "Code TODO", content: "TODO: ", keywords: "code todo developer" },

    // Symbols
    PickerItem { kind: ItemKind::Symbol, title: "Copyright", content: "©", keywords: "copyright کپی رایت" },
    PickerItem { kind: ItemKind::Symbol, title: "Registered", content: "®", keywords: "registered trademark" },
    PickerItem { kind: ItemKind::Symbol, title: "Trademark", content: "™", keywords: "trademark" },
    PickerItem { kind: ItemKind::Symbol, title: "Degree", content: "°", keywords: "degree temperature درجه" },
    PickerItem { kind: ItemKind::Symbol, title: "Plus minus", content: "±", keywords: "plus minus math مثبت منفی" },
    PickerItem { kind: ItemKind::Symbol, title: "Multiply", content: "×", keywords: "multiply times math ضرب" },
    PickerItem { kind: ItemKind::Symbol, title: "Divide", content: "÷", keywords: "divide math تقسیم" },
    PickerItem { kind: ItemKind::Symbol, title: "Approximately", content: "≈", keywords: "approximately math تقریبا" },
    PickerItem { kind: ItemKind::Symbol, title: "Not equal", content: "≠", keywords: "not equal math نامساوی" },
    PickerItem { kind: ItemKind::Symbol, title: "Less equal", content: "≤", keywords: "less equal math کوچکتر" },
    PickerItem { kind: ItemKind::Symbol, title: "Greater equal", content: "≥", keywords: "greater equal math بزرگتر" },
    PickerItem { kind: ItemKind::Symbol, title: "Infinity", content: "∞", keywords: "infinity math بی نهایت" },
    PickerItem { kind: ItemKind::Symbol, title: "Right arrow", content: "→", keywords: "right arrow فلش راست" },
    PickerItem { kind: ItemKind::Symbol, title: "Left arrow", content: "←", keywords: "left arrow فلش چپ" },
    PickerItem { kind: ItemKind::Symbol, title: "Up arrow", content: "↑", keywords: "up arrow فلش بالا" },
    PickerItem { kind: ItemKind::Symbol, title: "Down arrow", content: "↓", keywords: "down arrow فلش پایین" },
    PickerItem { kind: ItemKind::Symbol, title: "Bullet", content: "•", keywords: "bullet dot نقطه" },
    PickerItem { kind: ItemKind::Symbol, title: "Middle dot", content: "·", keywords: "middle dot نقطه" },
    PickerItem { kind: ItemKind::Symbol, title: "Section", content: "§", keywords: "section paragraph بخش" },
    PickerItem { kind: ItemKind::Symbol, title: "Paragraph", content: "¶", keywords: "paragraph pilcrow پاراگراف" },
];
